name = "taskmaster-api"
main = "index.js"
compatibility_date = "2024-12-01"

[vars]
GOOGLE_WEB_CLIENT_ID = "987569356526-2horbu7l43kh4l09kf4g366u2th1mvrl.apps.googleusercontent.com"

[[d1_databases]]
binding = "DB"
database_name = "taskmaster-db"
database_id = "ef726d35-666c-413b-a17d-48902597d449"
